name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        Configuration: [debug, release]
    env:
      StagingDirectory: buildartifacts 
      
    steps:
    - run: mkdir -p $env:StagingDirectory
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c ${{ matrix.Configuration }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Zip
      run: 7z a -tzip $env:StagingDirectory\InferNull.zip .\InferNull\bin\${{ matrix.Configuration }}\*
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: InferNull (${{ matrix.configuration }})
        path: ${{ env.StagingDirectory }}\InferNull.zip
        if-no-files-found: error
